#version: "3"
services:
  api:
    container_name: task-manager-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run dev
    env_file:
      - ./.env
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  database:
    container_name: MYSQL_DB
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    logging:
      driver: none

volumes:
  mysql_volume: