#version: "3"
services:
  api:
    container_name: task-manager-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run dev
    env_file:
      - ./.env
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  database:
    container_name: MYSQL_DB
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: local2020
      MYSQL_DATABASE: task_manager_db